### PR TITLE
Add Test Pilot URL to description

### LINKED ISSUE #174: Add reference to testpilot.firefox.com in addon meta
We have to add something to the `about:addons` page that 
1. Links back to https://testpilot.firefox.com.
2. Identifies this a Test Pilot experiment.

Exact specifications provided by @nchapman, @johngruen

### PR DESCRIPTION
**Pull request by jaredhirsch**
@chuckharmston quick R?

Fixes #174.

Screenshot in my about:addons with the line added:

screen shot 2016-05-03 at 12 47 44 pm

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@chuckharmston Actually, wait just a minute, I'll add the 1.0.3 release to the branch as well

**Comment by chuckharmston** [comment]
What's the point of having that URL there if it's not clickable? Can we just change the homepage instead?

**Comment by chuckharmston** [comment]
Oops, just saw the comments in the bug. Kind of crappy, still. @nchapman can we just change `em:homepageURL` instead and make reference to Test Pilot?

**Comment by jaredhirsch** [comment]
> What's the point of having that URL there if it's not clickable? Can we just change the homepage instead?

@chuckharmston See product request here https://github.com/mozilla/universal-search/issues/174#issuecomment-216641543

**Comment by jaredhirsch** [comment]
@chuckharmston I'm fine to put the text in both places, whatever

**Comment by chuckharmston** [comment]
Let's ship it so we don't have to block on product. We'll be doing another release soon for #165 anyway, we can fix then.

**Pull request merged**
