### PR TITLE
Adds architectural documentation (closes #93).

### LINKED ISSUE #93: Write architecture documentation
We should write documentation explaining the overall architecture of the project; specifically how the add-on and server work together.

### LINKED ISSUE #96: Recommendation shouldn't be highlighted until user arrows down
The default behavior highlights a row that corresponds to what would happen anyway if you hit Enter with the focus in the urlbar:

screen shot 2016-03-21 at 8 48 32 am

When we steal focus for the recommendation, it seems like hitting Enter would take you to the recommendation URL, but you actually have to key down, then back up, to get the recommendation URL into the urlbar (or click on it).
1. user types 'f'
   screen shot 2016-03-21 at 8 49 48 am
2. user keys down
   screen shot 2016-03-21 at 8 50 04 am
3. user keys back up to the recommendation, now the URL is in the urlbar
   screen shot 2016-03-21 at 8 50 08 am

Maybe the better interaction would be to not highlight the recommendation until the user hits the down arrow for the first time?

### PR DESCRIPTION
**Pull request by chuckharmston**
A first pass at this, anyway. I'm surely missing and misunderstanding things.

r? @6a68 cc @telliott @erikrose @twobraids @hannosch

### CODE REVIEW

**Comment by chuckharmston** [comment]
Can be browsed nicely here: https://github.com/chuckharmston/universal-search/blob/96-architecture-docs/README.md

**Comment by jaredhirsch** [comment]
@chuckharmston Thanks for taking a first pass at docs. I'll take a pass tomorrow morning, when I'm fresh.

**Comment by chuckharmston** [comment]
@6a68 Gentle reminder that this is still open :)

**Comment by jaredhirsch** [comment]
Thanks! Looks like I'm probably not going to get to it this week, lots of bugs left to fix in the current milestone

**Comment by jaredhirsch** [comment]
@chuckharmston A lot of the organizational changes in here seem to overlap with #152, and #152 is good to land after a rebase.

I'm not totally clear on the intended audience for the architecture.md file, as it discusses very low-level details, like the use of the `nsIWindowWatcher` Gecko component to iterate windows, but the description of other parts is very high level. For instance, the bug (#93) suggests that we should document how the addon and server interact, but this PR only lightly touches on that. We don't document the REST API or the syntax of the messages passed back and forth, for example.

I'm probably not going to have time to do a full pass of suggested edits this week. The code is pretty well-documented, and I think reading the code and code comments is probably a requirement for potential contributors; this is not an easy project to jump into.

I'd suggest we land the other reorganizational PR (#152) and maybe add some meat to #93 to clarify the audience for whom we would be documenting the addon-server interface. If you want to leave this open and discuss further in a few weeks, that's fine; if you'd rather close this and revisit later, that's fine too, your call.

**Comment by chuckharmston** [comment]
This has bitrot quite a bit over the past 2 months and is no longer relevant. WONTFIX.

**Pull request closed without merging**
